# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
 - main

pool: Test Pool 1

variables:
  imageName: 'pipelines-javascript-docker'

steps:
  - script: sudo chmod 666 /var/run/docker.sock

  - task: Docker@2
    displayName: Build an image
    inputs:
      repository: $(imageName)
      command: build
      Dockerfile: app/Dockerfile
